i386 QT_QPA_PLATFORMTHEME avahi ntpdate
furybsd/furybsd-livecd pull request #187
Opened 2020-09-14 23:09 UTC by probonopd

* Use separate ISO script for i386 (does not resolve the non-bootability described in #184 yet but might solve one component that adds to that issue
* Try to set `QT_QPA_PLATFORMTHEME` for Xfce to make Qt applications look native; does not seem to work yet (more investigation needed)
* Install and enable `avahi-daemon` in an effort to get local network browsing work in Xfce; for some reason a restart of `avahi-daemon` seems to be needed for it to work?
* Install and enable `ntpdate`
* Install all `dhcpcd` hooks in an effort to get the timezone from the DHCP server (I could not verify this yet since my server may or may not support this)

2020-09-14 23:34 UTC, probonopd commented
CI builds are "failing" because PRs are not allowed to upload to GitHub Releases, which is intentional.

I guess we need to script around that, so that they don't even attempt to.

2020-09-15 13:31 UTC, pkgdemon requested changes
@probonopd I think best practice is to change the value of ntpd_program and other relevant lines as shown here rather than disable ntpd explicitly.  This way if the user later enables ntpd it does not not override the default defined program, and it will be more clear that we change it if we can make this method work I think.

https://github.com/freebsd/freebsd/blob/releng/12.1/libexec/rc/rc.conf#L392

2020-09-15 17:30 UTC, pkgdemon approved these changes

2020-09-15 17:36 UTC, probonopd commented on overlays/uzip/furybsd-live-settings/files/usr/local/bin/furybsd-init-helper
> +/usr/sbin/sysrc -f /etc/rc.conf ntpd_enable="NO" >/dev/null 2>/dev/null # Seems to conflict with ntpdate
Not sure I can follow you here. When I just enabled `ntpd` _and_ `ntpdate`, the latter complained giving me the impression that the two cannot run at the same time. Hence I wanted to tell the system "do not run `ntpd` but do run `ntpdate`. 

I do not want a different `ntpd_program`, I do not want `ntpd` running at all.

Or am I misunderstanding something here?

2020-09-15 17:38 UTC, probonopd commented on overlays/uzip/furybsd-xfce-live-settings/files/usr/local/etc/profile.d/qt-qpa-platformtheme.sh
> +export QT_QPA_PLATFORMTHEME=gtk2
It does, but there is no working gtk2 QT_QPA_PLATFORMTHEME that I know of. Using this works for me on Linux with Xfce, gives a really native look to Qt applications on Xubuntu which is Xfce based. If we find a better way, we can always change it later.

What is worse, though, is that the environment variable does not seem to get exported into the Xfce session from here at all... any ideas why?

2020-09-15 17:40 UTC, probonopd commented on settings/packages.common
> +avahi-app
Ah, maybe this is why it is only half-working so far... How do we best ship that `/etc/nsswitch.conf `? Maybe it would be better to in-place _edit_ it?

2020-09-15 17:44 UTC, probonopd commented on build.sh
> +  sh "${cwd}/scripts/mkisoimages-${arch}.sh" -b "${label}" "${isopath}" "${cdroot}"
Yes, we are building them on Cirrus CI. The Cirrus CI host machine is amd64 but that should not hurt what is going on inside the chroot, right?

Adding `ls -lh /usr/src || true` to the build so that we can find out about that.

2020-09-15 17:51 UTC, pkgdemon commented on overlays/uzip/furybsd-live-settings/files/usr/local/bin/furybsd-init-helper
> +/usr/sbin/sysrc -f /etc/rc.conf ntpd_enable="NO" >/dev/null 2>/dev/null # Seems to conflict with ntpdate
You might have a point.  I think this knob is specific from running ntpd from ports/pkg and not openntpd.  Nothing to see here.  :) https://forums.freebsd.org/threads/ntpd-not-syncing-on-startup.68933/

2020-09-15 17:55 UTC, pkgdemon commented on overlays/uzip/furybsd-xfce-live-settings/files/usr/local/etc/profile.d/qt-qpa-platformtheme.sh
> +export QT_QPA_PLATFORMTHEME=gtk2
Could it be because of the user shell?  I normally would do this this way....

/usrl/local/etc/xdg/autostart/furybsd-xfce-settings.desktop 
/usr/local/bin/furybsd-xfce-settings.sh (which get's launched by .desktop xdg file) let me know if you need an example

Then install these into uzip/overlays/furybsd-installed-settings/ and run chmod +x to make them executable so that they get generated by the XFCE package only.  Wouldn't that do the trick?

2020-09-15 17:57 UTC, pkgdemon commented on settings/packages.common
> +avahi-app
I would probably ship the modified `/etc/nsswitch.conf` in uzip/furybsd-settings/etc/nsswitch.conf` so that it can be used in all desktops.

2020-09-15 17:58 UTC, pkgdemon commented on build.sh
> +  sh "${cwd}/scripts/mkisoimages-${arch}.sh" -b "${label}" "${isopath}" "${cdroot}"
Can CIRRUS CI run i386 builds on i386, arm on arm, etc?   Or is that too complicated?

2020-09-15 18:06 UTC, probonopd commented on settings/packages.common
> +avahi-app
Added

2020-09-15 18:10 UTC, probonopd commented on overlays/uzip/furybsd-xfce-live-settings/files/usr/local/etc/profile.d/qt-qpa-platformtheme.sh
> +export QT_QPA_PLATFORMTHEME=gtk2
I don't think so because that script would be executed "in parallel" to other stuff, it would not result in the exported variable becoming part of the environment that apps launched in Xfce see.

2020-09-15 18:14 UTC, probonopd commented on build.sh
> +  sh "${cwd}/scripts/mkisoimages-${arch}.sh" -b "${label}" "${isopath}" "${cdroot}"
The answer is yes, it does come with `/usr/src` installed.

2020-09-15 18:17 UTC, probonopd commented on overlays/uzip/furybsd-xfce-live-settings/files/usr/local/etc/profile.d/qt-qpa-platformtheme.sh
> +export QT_QPA_PLATFORMTHEME=gtk2
`/usr/local/etc/X11/xinit/xinitrc.d/...` might be the place to be.

2020-09-15 18:23 UTC, pkgdemon commented on build.sh
> +  sh "${cwd}/scripts/mkisoimages-${arch}.sh" -b "${label}" "${isopath}" "${cdroot}"
> The answer is yes, it does come with `/usr/src` installed: https://api.cirrus-ci.com/v1/task/5798861140656128/logs/install.log

That seems promising.  Is it also possible make cirrus CI launch arch specific builders like this?

FuryBSD-LUMINA-12.1-amd64 -> amd64 builder
FuryBSD-LUMINA-12.1-i386 -> i386 builder
FuryBSD-MATE-12.1-amd64 -> amd64 builder
FuryBSD-MATE-12.1-i386 -> i386 builder
FuryBSD-XFCE-12.1-amd64 -> amd64 builder
FuryBSD-XFCE-12.1-i386 -> i386 builder

2020-09-15 18:30 UTC, probonopd commented on build.sh
> +  sh "${cwd}/scripts/mkisoimages-${arch}.sh" -b "${label}" "${isopath}" "${cdroot}"
The question is whether there are 32-bit FreeBSD images on Google Cloud Engine, which is what Cirrus CI uses.

https://cirrus-ci.org/guide/FreeBSD/

2020-09-15 18:33 UTC, probonopd commented on build.sh
> +  sh "${cwd}/scripts/mkisoimages-${arch}.sh" -b "${label}" "${isopath}" "${cdroot}"
Maybe we just try with `freebsd-12-1-release-amd64` and `freebsd-12-1-release-i386` and see what happens...

2020-09-15 18:35 UTC, pkgdemon commented on build.sh
> +  sh "${cwd}/scripts/mkisoimages-${arch}.sh" -b "${label}" "${isopath}" "${cdroot}"
I will check an ubuntu vm with gcloud installed to see if I can get a full list by running this command:

```
gcloud compute images list --project freebsd-org-cloud-dev --no-standard-images
```

2020-09-15 18:38 UTC, probonopd commented on build.sh
> +  sh "${cwd}/scripts/mkisoimages-${arch}.sh" -b "${label}" "${isopath}" "${cdroot}"
`gcloud compute images list --project freebsd-org-cloud-dev --no-standard-
images` lists only amd64 images. So the answer is probably no, at least not without adding own runners.

2020-09-15 18:39 UTC, probonopd commented
Thanks for your remarks, very valuable! Please let me know if you would like to see any other changes.

2020-09-15 18:46 UTC, pkgdemon commented on build.sh
> +  sh "${cwd}/scripts/mkisoimages-${arch}.sh" -b "${label}" "${isopath}" "${cdroot}"
Long story short if we could build i386 on i386 with sources included I was thinking we could make a case statement under the image function to do the right thing for amd64, i386, but also call the mkisoimages.sh for the appropriate version on the host under /usr/src instead of shipping that in our scripts?

We can then document using an example such as this on how to apply the missing source if not installed on the builder.

https://nanxiao.gitbooks.io/freebsd-101-hacks/content/posts/install-source-code.html

We can also add a simple check just to make sure sources exist when running build.sh?

2020-09-15 18:48 UTC, probonopd commented on build.sh
> +  sh "${cwd}/scripts/mkisoimages-${arch}.sh" -b "${label}" "${isopath}" "${cdroot}"
Having to download the whole FreeBSD source code just for 2 shell scripts seems a bit wasteful to me.

2020-09-15 19:14 UTC, pkgdemon commented on build.sh
> +  sh "${cwd}/scripts/mkisoimages-${arch}.sh" -b "${label}" "${isopath}" "${cdroot}"
As discussed in IRC different major versions of FreeBSD will have different versions of the mkisoimages.sh script.  It adds another point of failure, maintenance.  Also bringing in i386 support for hybrid ISO into FuryBSD itself will not be trivial as there were a number of commits in FreeBSD to add this support.  The following may not be a complete list but it should give a rough idea.

https://reviews.freebsd.org/D15051
https://reviews.freebsd.org/rS332661
https://reviews.freebsd.org/rS331949
https://reviews.freebsd.org/D14799
https://reviews.freebsd.org/rS332084

Second I think as discussed we should using grub2 for at least the iso media.  This would more simply address hybrid boot media needs for i386 as well as likely enhance compatibility issues where bsdloader fails.  Or drop the idea of support i386, or pursue that fix properly in FreeBSD.  Those are the options I think.  For now we can take this work as is I just don't think it's optimal.

2020-09-15 19:33 UTC, merged